# Generated by Django 2.0.7 on 2018-07-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180717_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurb',
            field=models.TextField(default='Test blurb', help_text='Short blurb summarizing article for list view', max_length=200),
            preserve_default=False,
        ),
    ]
