# Generated by Django 2.0 on 2018-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180721_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='stack_overflow',
            field=models.URLField(blank=True, null=True),
        ),
    ]
