# Generated by Django 2.1.3 on 2018-11-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180721_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagulous_Post_tags',
            new_name='SiteTags',
        ),
    ]
