# Generated by Django 2.1.3 on 2018-11-19 01:14

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(help_text='Hyphen-separated string of keywords for SEO', max_length=40)),
                ('resource_author', models.CharField(blank=True, max_length=100, null=True)),
                ('blurb', models.TextField(help_text='Short blurb summarizing review for list view', max_length=200)),
                ('content', markdownx.models.MarkdownxField()),
                ('last_updated', models.DateField()),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Resource')),
            ],
        ),
    ]
