# Generated by Django 2.1.3 on 2018-12-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20181118_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
