# Generated by Django 2.1.3 on 2018-12-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='blurb',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
